set_property SRC_FILE_INFO {cfile:D:/OpalFolder/MyOwnProject/FPGA/GALS_Packet-Based_Fabric/GALS_Packet-Based_Fabric.srcs/constrs_1/new/arty.xdc rfile:../../../GALS_Packet-Based_Fabric.srcs/constrs_1/new/arty.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN E3 IOSTANDARD LVCMOS33} [get_ports clk_100mhz]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C2 IOSTANDARD LVCMOS33} [get_ports rst_n_btn]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H5 IOSTANDARD LVCMOS33} [get_ports {led[0]}]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J5 IOSTANDARD LVCMOS33} [get_ports {led[1]}]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T9 IOSTANDARD LVCMOS33} [get_ports {led[2]}]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T10 IOSTANDARD LVCMOS33} [get_ports {led[3]}]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D10 IOSTANDARD LVCMOS33} [get_ports uart_txd]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A9 IOSTANDARD LVCMOS33} [get_ports uart_rxd]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list clk_gen/inst/clk_out4]]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {u_stress/agent_10/rx_err_cnt[0]} {u_stress/agent_10/rx_err_cnt[1]} {u_stress/agent_10/rx_err_cnt[2]} {u_stress/agent_10/rx_err_cnt[3]} {u_stress/agent_10/rx_err_cnt[4]} {u_stress/agent_10/rx_err_cnt[5]} {u_stress/agent_10/rx_err_cnt[6]} {u_stress/agent_10/rx_err_cnt[7]} {u_stress/agent_10/rx_err_cnt[8]} {u_stress/agent_10/rx_err_cnt[9]} {u_stress/agent_10/rx_err_cnt[10]} {u_stress/agent_10/rx_err_cnt[11]} {u_stress/agent_10/rx_err_cnt[12]} {u_stress/agent_10/rx_err_cnt[13]} {u_stress/agent_10/rx_err_cnt[14]} {u_stress/agent_10/rx_err_cnt[15]} {u_stress/agent_10/rx_err_cnt[16]} {u_stress/agent_10/rx_err_cnt[17]} {u_stress/agent_10/rx_err_cnt[18]} {u_stress/agent_10/rx_err_cnt[19]} {u_stress/agent_10/rx_err_cnt[20]} {u_stress/agent_10/rx_err_cnt[21]} {u_stress/agent_10/rx_err_cnt[22]} {u_stress/agent_10/rx_err_cnt[23]} {u_stress/agent_10/rx_err_cnt[24]} {u_stress/agent_10/rx_err_cnt[25]} {u_stress/agent_10/rx_err_cnt[26]} {u_stress/agent_10/rx_err_cnt[27]} {u_stress/agent_10/rx_err_cnt[28]} {u_stress/agent_10/rx_err_cnt[29]} {u_stress/agent_10/rx_err_cnt[30]} {u_stress/agent_10/rx_err_cnt[31]}]]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {u_stress/agent_10/state_dbg[0]} {u_stress/agent_10/state_dbg[1]}]]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {u_stress/agent_10/rx_vc0_cnt[0]} {u_stress/agent_10/rx_vc0_cnt[1]} {u_stress/agent_10/rx_vc0_cnt[2]} {u_stress/agent_10/rx_vc0_cnt[3]} {u_stress/agent_10/rx_vc0_cnt[4]} {u_stress/agent_10/rx_vc0_cnt[5]} {u_stress/agent_10/rx_vc0_cnt[6]} {u_stress/agent_10/rx_vc0_cnt[7]} {u_stress/agent_10/rx_vc0_cnt[8]} {u_stress/agent_10/rx_vc0_cnt[9]} {u_stress/agent_10/rx_vc0_cnt[10]} {u_stress/agent_10/rx_vc0_cnt[11]} {u_stress/agent_10/rx_vc0_cnt[12]} {u_stress/agent_10/rx_vc0_cnt[13]} {u_stress/agent_10/rx_vc0_cnt[14]} {u_stress/agent_10/rx_vc0_cnt[15]} {u_stress/agent_10/rx_vc0_cnt[16]} {u_stress/agent_10/rx_vc0_cnt[17]} {u_stress/agent_10/rx_vc0_cnt[18]} {u_stress/agent_10/rx_vc0_cnt[19]} {u_stress/agent_10/rx_vc0_cnt[20]} {u_stress/agent_10/rx_vc0_cnt[21]} {u_stress/agent_10/rx_vc0_cnt[22]} {u_stress/agent_10/rx_vc0_cnt[23]} {u_stress/agent_10/rx_vc0_cnt[24]} {u_stress/agent_10/rx_vc0_cnt[25]} {u_stress/agent_10/rx_vc0_cnt[26]} {u_stress/agent_10/rx_vc0_cnt[27]} {u_stress/agent_10/rx_vc0_cnt[28]} {u_stress/agent_10/rx_vc0_cnt[29]} {u_stress/agent_10/rx_vc0_cnt[30]} {u_stress/agent_10/rx_vc0_cnt[31]}]]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {u_stress/agent_10/rx_vc1_cnt[0]} {u_stress/agent_10/rx_vc1_cnt[1]} {u_stress/agent_10/rx_vc1_cnt[2]} {u_stress/agent_10/rx_vc1_cnt[3]} {u_stress/agent_10/rx_vc1_cnt[4]} {u_stress/agent_10/rx_vc1_cnt[5]} {u_stress/agent_10/rx_vc1_cnt[6]} {u_stress/agent_10/rx_vc1_cnt[7]} {u_stress/agent_10/rx_vc1_cnt[8]} {u_stress/agent_10/rx_vc1_cnt[9]} {u_stress/agent_10/rx_vc1_cnt[10]} {u_stress/agent_10/rx_vc1_cnt[11]} {u_stress/agent_10/rx_vc1_cnt[12]} {u_stress/agent_10/rx_vc1_cnt[13]} {u_stress/agent_10/rx_vc1_cnt[14]} {u_stress/agent_10/rx_vc1_cnt[15]} {u_stress/agent_10/rx_vc1_cnt[16]} {u_stress/agent_10/rx_vc1_cnt[17]} {u_stress/agent_10/rx_vc1_cnt[18]} {u_stress/agent_10/rx_vc1_cnt[19]} {u_stress/agent_10/rx_vc1_cnt[20]} {u_stress/agent_10/rx_vc1_cnt[21]} {u_stress/agent_10/rx_vc1_cnt[22]} {u_stress/agent_10/rx_vc1_cnt[23]} {u_stress/agent_10/rx_vc1_cnt[24]} {u_stress/agent_10/rx_vc1_cnt[25]} {u_stress/agent_10/rx_vc1_cnt[26]} {u_stress/agent_10/rx_vc1_cnt[27]} {u_stress/agent_10/rx_vc1_cnt[28]} {u_stress/agent_10/rx_vc1_cnt[29]} {u_stress/agent_10/rx_vc1_cnt[30]} {u_stress/agent_10/rx_vc1_cnt[31]}]]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {u_stress/agent_10/tx_stall_cnt[0]} {u_stress/agent_10/tx_stall_cnt[1]} {u_stress/agent_10/tx_stall_cnt[2]} {u_stress/agent_10/tx_stall_cnt[3]} {u_stress/agent_10/tx_stall_cnt[4]} {u_stress/agent_10/tx_stall_cnt[5]} {u_stress/agent_10/tx_stall_cnt[6]} {u_stress/agent_10/tx_stall_cnt[7]} {u_stress/agent_10/tx_stall_cnt[8]} {u_stress/agent_10/tx_stall_cnt[9]} {u_stress/agent_10/tx_stall_cnt[10]} {u_stress/agent_10/tx_stall_cnt[11]} {u_stress/agent_10/tx_stall_cnt[12]} {u_stress/agent_10/tx_stall_cnt[13]} {u_stress/agent_10/tx_stall_cnt[14]} {u_stress/agent_10/tx_stall_cnt[15]} {u_stress/agent_10/tx_stall_cnt[16]} {u_stress/agent_10/tx_stall_cnt[17]} {u_stress/agent_10/tx_stall_cnt[18]} {u_stress/agent_10/tx_stall_cnt[19]} {u_stress/agent_10/tx_stall_cnt[20]} {u_stress/agent_10/tx_stall_cnt[21]} {u_stress/agent_10/tx_stall_cnt[22]} {u_stress/agent_10/tx_stall_cnt[23]} {u_stress/agent_10/tx_stall_cnt[24]} {u_stress/agent_10/tx_stall_cnt[25]} {u_stress/agent_10/tx_stall_cnt[26]} {u_stress/agent_10/tx_stall_cnt[27]} {u_stress/agent_10/tx_stall_cnt[28]} {u_stress/agent_10/tx_stall_cnt[29]} {u_stress/agent_10/tx_stall_cnt[30]} {u_stress/agent_10/tx_stall_cnt[31]}]]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {u_stress/agent_10/tx_flit_cnt[0]} {u_stress/agent_10/tx_flit_cnt[1]} {u_stress/agent_10/tx_flit_cnt[2]} {u_stress/agent_10/tx_flit_cnt[3]} {u_stress/agent_10/tx_flit_cnt[4]} {u_stress/agent_10/tx_flit_cnt[5]} {u_stress/agent_10/tx_flit_cnt[6]} {u_stress/agent_10/tx_flit_cnt[7]} {u_stress/agent_10/tx_flit_cnt[8]} {u_stress/agent_10/tx_flit_cnt[9]} {u_stress/agent_10/tx_flit_cnt[10]} {u_stress/agent_10/tx_flit_cnt[11]} {u_stress/agent_10/tx_flit_cnt[12]} {u_stress/agent_10/tx_flit_cnt[13]} {u_stress/agent_10/tx_flit_cnt[14]} {u_stress/agent_10/tx_flit_cnt[15]} {u_stress/agent_10/tx_flit_cnt[16]} {u_stress/agent_10/tx_flit_cnt[17]} {u_stress/agent_10/tx_flit_cnt[18]} {u_stress/agent_10/tx_flit_cnt[19]} {u_stress/agent_10/tx_flit_cnt[20]} {u_stress/agent_10/tx_flit_cnt[21]} {u_stress/agent_10/tx_flit_cnt[22]} {u_stress/agent_10/tx_flit_cnt[23]} {u_stress/agent_10/tx_flit_cnt[24]} {u_stress/agent_10/tx_flit_cnt[25]} {u_stress/agent_10/tx_flit_cnt[26]} {u_stress/agent_10/tx_flit_cnt[27]} {u_stress/agent_10/tx_flit_cnt[28]} {u_stress/agent_10/tx_flit_cnt[29]} {u_stress/agent_10/tx_flit_cnt[30]} {u_stress/agent_10/tx_flit_cnt[31]}]]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {u_stress/agent_10/rx_tdest_dbg[0]} {u_stress/agent_10/rx_tdest_dbg[1]} {u_stress/agent_10/rx_tdest_dbg[2]} {u_stress/agent_10/rx_tdest_dbg[3]}]]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list u_stress/agent_10/test_done]]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_1 ila
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/clk [get_nets [list clk_gen/inst/clk_out3]]
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_1/probe0]
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe0 [get_nets [list {u_stress/agent_01/rx_vc0_cnt[0]} {u_stress/agent_01/rx_vc0_cnt[1]} {u_stress/agent_01/rx_vc0_cnt[2]} {u_stress/agent_01/rx_vc0_cnt[3]} {u_stress/agent_01/rx_vc0_cnt[4]} {u_stress/agent_01/rx_vc0_cnt[5]} {u_stress/agent_01/rx_vc0_cnt[6]} {u_stress/agent_01/rx_vc0_cnt[7]} {u_stress/agent_01/rx_vc0_cnt[8]} {u_stress/agent_01/rx_vc0_cnt[9]} {u_stress/agent_01/rx_vc0_cnt[10]} {u_stress/agent_01/rx_vc0_cnt[11]} {u_stress/agent_01/rx_vc0_cnt[12]} {u_stress/agent_01/rx_vc0_cnt[13]} {u_stress/agent_01/rx_vc0_cnt[14]} {u_stress/agent_01/rx_vc0_cnt[15]} {u_stress/agent_01/rx_vc0_cnt[16]} {u_stress/agent_01/rx_vc0_cnt[17]} {u_stress/agent_01/rx_vc0_cnt[18]} {u_stress/agent_01/rx_vc0_cnt[19]} {u_stress/agent_01/rx_vc0_cnt[20]} {u_stress/agent_01/rx_vc0_cnt[21]} {u_stress/agent_01/rx_vc0_cnt[22]} {u_stress/agent_01/rx_vc0_cnt[23]} {u_stress/agent_01/rx_vc0_cnt[24]} {u_stress/agent_01/rx_vc0_cnt[25]} {u_stress/agent_01/rx_vc0_cnt[26]} {u_stress/agent_01/rx_vc0_cnt[27]} {u_stress/agent_01/rx_vc0_cnt[28]} {u_stress/agent_01/rx_vc0_cnt[29]} {u_stress/agent_01/rx_vc0_cnt[30]} {u_stress/agent_01/rx_vc0_cnt[31]}]]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_1/probe1]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe1 [get_nets [list {u_stress/agent_01/rx_vc1_cnt[0]} {u_stress/agent_01/rx_vc1_cnt[1]} {u_stress/agent_01/rx_vc1_cnt[2]} {u_stress/agent_01/rx_vc1_cnt[3]} {u_stress/agent_01/rx_vc1_cnt[4]} {u_stress/agent_01/rx_vc1_cnt[5]} {u_stress/agent_01/rx_vc1_cnt[6]} {u_stress/agent_01/rx_vc1_cnt[7]} {u_stress/agent_01/rx_vc1_cnt[8]} {u_stress/agent_01/rx_vc1_cnt[9]} {u_stress/agent_01/rx_vc1_cnt[10]} {u_stress/agent_01/rx_vc1_cnt[11]} {u_stress/agent_01/rx_vc1_cnt[12]} {u_stress/agent_01/rx_vc1_cnt[13]} {u_stress/agent_01/rx_vc1_cnt[14]} {u_stress/agent_01/rx_vc1_cnt[15]} {u_stress/agent_01/rx_vc1_cnt[16]} {u_stress/agent_01/rx_vc1_cnt[17]} {u_stress/agent_01/rx_vc1_cnt[18]} {u_stress/agent_01/rx_vc1_cnt[19]} {u_stress/agent_01/rx_vc1_cnt[20]} {u_stress/agent_01/rx_vc1_cnt[21]} {u_stress/agent_01/rx_vc1_cnt[22]} {u_stress/agent_01/rx_vc1_cnt[23]} {u_stress/agent_01/rx_vc1_cnt[24]} {u_stress/agent_01/rx_vc1_cnt[25]} {u_stress/agent_01/rx_vc1_cnt[26]} {u_stress/agent_01/rx_vc1_cnt[27]} {u_stress/agent_01/rx_vc1_cnt[28]} {u_stress/agent_01/rx_vc1_cnt[29]} {u_stress/agent_01/rx_vc1_cnt[30]} {u_stress/agent_01/rx_vc1_cnt[31]}]]
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe2]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_1/probe2]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe2 [get_nets [list {u_stress/agent_01/state_dbg[0]} {u_stress/agent_01/state_dbg[1]}]]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe3]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_1/probe3]
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe3 [get_nets [list {u_stress/agent_01/rx_err_cnt[0]} {u_stress/agent_01/rx_err_cnt[1]} {u_stress/agent_01/rx_err_cnt[2]} {u_stress/agent_01/rx_err_cnt[3]} {u_stress/agent_01/rx_err_cnt[4]} {u_stress/agent_01/rx_err_cnt[5]} {u_stress/agent_01/rx_err_cnt[6]} {u_stress/agent_01/rx_err_cnt[7]} {u_stress/agent_01/rx_err_cnt[8]} {u_stress/agent_01/rx_err_cnt[9]} {u_stress/agent_01/rx_err_cnt[10]} {u_stress/agent_01/rx_err_cnt[11]} {u_stress/agent_01/rx_err_cnt[12]} {u_stress/agent_01/rx_err_cnt[13]} {u_stress/agent_01/rx_err_cnt[14]} {u_stress/agent_01/rx_err_cnt[15]} {u_stress/agent_01/rx_err_cnt[16]} {u_stress/agent_01/rx_err_cnt[17]} {u_stress/agent_01/rx_err_cnt[18]} {u_stress/agent_01/rx_err_cnt[19]} {u_stress/agent_01/rx_err_cnt[20]} {u_stress/agent_01/rx_err_cnt[21]} {u_stress/agent_01/rx_err_cnt[22]} {u_stress/agent_01/rx_err_cnt[23]} {u_stress/agent_01/rx_err_cnt[24]} {u_stress/agent_01/rx_err_cnt[25]} {u_stress/agent_01/rx_err_cnt[26]} {u_stress/agent_01/rx_err_cnt[27]} {u_stress/agent_01/rx_err_cnt[28]} {u_stress/agent_01/rx_err_cnt[29]} {u_stress/agent_01/rx_err_cnt[30]} {u_stress/agent_01/rx_err_cnt[31]}]]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe4]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_1/probe4]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe4 [get_nets [list {u_stress/agent_01/tx_stall_cnt[0]} {u_stress/agent_01/tx_stall_cnt[1]} {u_stress/agent_01/tx_stall_cnt[2]} {u_stress/agent_01/tx_stall_cnt[3]} {u_stress/agent_01/tx_stall_cnt[4]} {u_stress/agent_01/tx_stall_cnt[5]} {u_stress/agent_01/tx_stall_cnt[6]} {u_stress/agent_01/tx_stall_cnt[7]} {u_stress/agent_01/tx_stall_cnt[8]} {u_stress/agent_01/tx_stall_cnt[9]} {u_stress/agent_01/tx_stall_cnt[10]} {u_stress/agent_01/tx_stall_cnt[11]} {u_stress/agent_01/tx_stall_cnt[12]} {u_stress/agent_01/tx_stall_cnt[13]} {u_stress/agent_01/tx_stall_cnt[14]} {u_stress/agent_01/tx_stall_cnt[15]} {u_stress/agent_01/tx_stall_cnt[16]} {u_stress/agent_01/tx_stall_cnt[17]} {u_stress/agent_01/tx_stall_cnt[18]} {u_stress/agent_01/tx_stall_cnt[19]} {u_stress/agent_01/tx_stall_cnt[20]} {u_stress/agent_01/tx_stall_cnt[21]} {u_stress/agent_01/tx_stall_cnt[22]} {u_stress/agent_01/tx_stall_cnt[23]} {u_stress/agent_01/tx_stall_cnt[24]} {u_stress/agent_01/tx_stall_cnt[25]} {u_stress/agent_01/tx_stall_cnt[26]} {u_stress/agent_01/tx_stall_cnt[27]} {u_stress/agent_01/tx_stall_cnt[28]} {u_stress/agent_01/tx_stall_cnt[29]} {u_stress/agent_01/tx_stall_cnt[30]} {u_stress/agent_01/tx_stall_cnt[31]}]]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe5]
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_1/probe5]
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe5 [get_nets [list {u_stress/agent_01/tx_flit_cnt[0]} {u_stress/agent_01/tx_flit_cnt[1]} {u_stress/agent_01/tx_flit_cnt[2]} {u_stress/agent_01/tx_flit_cnt[3]} {u_stress/agent_01/tx_flit_cnt[4]} {u_stress/agent_01/tx_flit_cnt[5]} {u_stress/agent_01/tx_flit_cnt[6]} {u_stress/agent_01/tx_flit_cnt[7]} {u_stress/agent_01/tx_flit_cnt[8]} {u_stress/agent_01/tx_flit_cnt[9]} {u_stress/agent_01/tx_flit_cnt[10]} {u_stress/agent_01/tx_flit_cnt[11]} {u_stress/agent_01/tx_flit_cnt[12]} {u_stress/agent_01/tx_flit_cnt[13]} {u_stress/agent_01/tx_flit_cnt[14]} {u_stress/agent_01/tx_flit_cnt[15]} {u_stress/agent_01/tx_flit_cnt[16]} {u_stress/agent_01/tx_flit_cnt[17]} {u_stress/agent_01/tx_flit_cnt[18]} {u_stress/agent_01/tx_flit_cnt[19]} {u_stress/agent_01/tx_flit_cnt[20]} {u_stress/agent_01/tx_flit_cnt[21]} {u_stress/agent_01/tx_flit_cnt[22]} {u_stress/agent_01/tx_flit_cnt[23]} {u_stress/agent_01/tx_flit_cnt[24]} {u_stress/agent_01/tx_flit_cnt[25]} {u_stress/agent_01/tx_flit_cnt[26]} {u_stress/agent_01/tx_flit_cnt[27]} {u_stress/agent_01/tx_flit_cnt[28]} {u_stress/agent_01/tx_flit_cnt[29]} {u_stress/agent_01/tx_flit_cnt[30]} {u_stress/agent_01/tx_flit_cnt[31]}]]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe6]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_1/probe6]
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe6 [get_nets [list {u_stress/agent_01/rx_tdest_dbg[0]} {u_stress/agent_01/rx_tdest_dbg[1]} {u_stress/agent_01/rx_tdest_dbg[2]} {u_stress/agent_01/rx_tdest_dbg[3]}]]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe7]
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1/probe7]
set_property src_info {type:XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe7 [get_nets [list u_stress/agent_01/test_done]]
set_property src_info {type:XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_2 ila
set_property src_info {type:XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_2/clk]
set_property src_info {type:XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/clk [get_nets [list clk_gen/inst/clk_out2]]
set_property src_info {type:XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe0]
set_property src_info {type:XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_2/probe0]
set_property src_info {type:XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe0 [get_nets [list {u_stress/agent_00/rx_tdest_dbg[0]} {u_stress/agent_00/rx_tdest_dbg[1]} {u_stress/agent_00/rx_tdest_dbg[2]} {u_stress/agent_00/rx_tdest_dbg[3]}]]
set_property src_info {type:XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_2 probe
set_property src_info {type:XDC file:1 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe1]
set_property src_info {type:XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_2/probe1]
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe1 [get_nets [list {u_stress/agent_00/rx_vc0_cnt[0]} {u_stress/agent_00/rx_vc0_cnt[1]} {u_stress/agent_00/rx_vc0_cnt[2]} {u_stress/agent_00/rx_vc0_cnt[3]} {u_stress/agent_00/rx_vc0_cnt[4]} {u_stress/agent_00/rx_vc0_cnt[5]} {u_stress/agent_00/rx_vc0_cnt[6]} {u_stress/agent_00/rx_vc0_cnt[7]} {u_stress/agent_00/rx_vc0_cnt[8]} {u_stress/agent_00/rx_vc0_cnt[9]} {u_stress/agent_00/rx_vc0_cnt[10]} {u_stress/agent_00/rx_vc0_cnt[11]} {u_stress/agent_00/rx_vc0_cnt[12]} {u_stress/agent_00/rx_vc0_cnt[13]} {u_stress/agent_00/rx_vc0_cnt[14]} {u_stress/agent_00/rx_vc0_cnt[15]} {u_stress/agent_00/rx_vc0_cnt[16]} {u_stress/agent_00/rx_vc0_cnt[17]} {u_stress/agent_00/rx_vc0_cnt[18]} {u_stress/agent_00/rx_vc0_cnt[19]} {u_stress/agent_00/rx_vc0_cnt[20]} {u_stress/agent_00/rx_vc0_cnt[21]} {u_stress/agent_00/rx_vc0_cnt[22]} {u_stress/agent_00/rx_vc0_cnt[23]} {u_stress/agent_00/rx_vc0_cnt[24]} {u_stress/agent_00/rx_vc0_cnt[25]} {u_stress/agent_00/rx_vc0_cnt[26]} {u_stress/agent_00/rx_vc0_cnt[27]} {u_stress/agent_00/rx_vc0_cnt[28]} {u_stress/agent_00/rx_vc0_cnt[29]} {u_stress/agent_00/rx_vc0_cnt[30]} {u_stress/agent_00/rx_vc0_cnt[31]}]]
set_property src_info {type:XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_2 probe
set_property src_info {type:XDC file:1 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe2]
set_property src_info {type:XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_2/probe2]
set_property src_info {type:XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe2 [get_nets [list {u_stress/agent_00/rx_vc1_cnt[0]} {u_stress/agent_00/rx_vc1_cnt[1]} {u_stress/agent_00/rx_vc1_cnt[2]} {u_stress/agent_00/rx_vc1_cnt[3]} {u_stress/agent_00/rx_vc1_cnt[4]} {u_stress/agent_00/rx_vc1_cnt[5]} {u_stress/agent_00/rx_vc1_cnt[6]} {u_stress/agent_00/rx_vc1_cnt[7]} {u_stress/agent_00/rx_vc1_cnt[8]} {u_stress/agent_00/rx_vc1_cnt[9]} {u_stress/agent_00/rx_vc1_cnt[10]} {u_stress/agent_00/rx_vc1_cnt[11]} {u_stress/agent_00/rx_vc1_cnt[12]} {u_stress/agent_00/rx_vc1_cnt[13]} {u_stress/agent_00/rx_vc1_cnt[14]} {u_stress/agent_00/rx_vc1_cnt[15]} {u_stress/agent_00/rx_vc1_cnt[16]} {u_stress/agent_00/rx_vc1_cnt[17]} {u_stress/agent_00/rx_vc1_cnt[18]} {u_stress/agent_00/rx_vc1_cnt[19]} {u_stress/agent_00/rx_vc1_cnt[20]} {u_stress/agent_00/rx_vc1_cnt[21]} {u_stress/agent_00/rx_vc1_cnt[22]} {u_stress/agent_00/rx_vc1_cnt[23]} {u_stress/agent_00/rx_vc1_cnt[24]} {u_stress/agent_00/rx_vc1_cnt[25]} {u_stress/agent_00/rx_vc1_cnt[26]} {u_stress/agent_00/rx_vc1_cnt[27]} {u_stress/agent_00/rx_vc1_cnt[28]} {u_stress/agent_00/rx_vc1_cnt[29]} {u_stress/agent_00/rx_vc1_cnt[30]} {u_stress/agent_00/rx_vc1_cnt[31]}]]
set_property src_info {type:XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_2 probe
set_property src_info {type:XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe3]
set_property src_info {type:XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_2/probe3]
set_property src_info {type:XDC file:1 line:134 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe3 [get_nets [list {u_stress/agent_00/rx_err_cnt[0]} {u_stress/agent_00/rx_err_cnt[1]} {u_stress/agent_00/rx_err_cnt[2]} {u_stress/agent_00/rx_err_cnt[3]} {u_stress/agent_00/rx_err_cnt[4]} {u_stress/agent_00/rx_err_cnt[5]} {u_stress/agent_00/rx_err_cnt[6]} {u_stress/agent_00/rx_err_cnt[7]} {u_stress/agent_00/rx_err_cnt[8]} {u_stress/agent_00/rx_err_cnt[9]} {u_stress/agent_00/rx_err_cnt[10]} {u_stress/agent_00/rx_err_cnt[11]} {u_stress/agent_00/rx_err_cnt[12]} {u_stress/agent_00/rx_err_cnt[13]} {u_stress/agent_00/rx_err_cnt[14]} {u_stress/agent_00/rx_err_cnt[15]} {u_stress/agent_00/rx_err_cnt[16]} {u_stress/agent_00/rx_err_cnt[17]} {u_stress/agent_00/rx_err_cnt[18]} {u_stress/agent_00/rx_err_cnt[19]} {u_stress/agent_00/rx_err_cnt[20]} {u_stress/agent_00/rx_err_cnt[21]} {u_stress/agent_00/rx_err_cnt[22]} {u_stress/agent_00/rx_err_cnt[23]} {u_stress/agent_00/rx_err_cnt[24]} {u_stress/agent_00/rx_err_cnt[25]} {u_stress/agent_00/rx_err_cnt[26]} {u_stress/agent_00/rx_err_cnt[27]} {u_stress/agent_00/rx_err_cnt[28]} {u_stress/agent_00/rx_err_cnt[29]} {u_stress/agent_00/rx_err_cnt[30]} {u_stress/agent_00/rx_err_cnt[31]}]]
set_property src_info {type:XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_2 probe
set_property src_info {type:XDC file:1 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe4]
set_property src_info {type:XDC file:1 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_2/probe4]
set_property src_info {type:XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe4 [get_nets [list {u_stress/agent_00/state_dbg[0]} {u_stress/agent_00/state_dbg[1]}]]
set_property src_info {type:XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_2 probe
set_property src_info {type:XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe5]
set_property src_info {type:XDC file:1 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_2/probe5]
set_property src_info {type:XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe5 [get_nets [list {u_stress/agent_00/tx_flit_cnt[0]} {u_stress/agent_00/tx_flit_cnt[1]} {u_stress/agent_00/tx_flit_cnt[2]} {u_stress/agent_00/tx_flit_cnt[3]} {u_stress/agent_00/tx_flit_cnt[4]} {u_stress/agent_00/tx_flit_cnt[5]} {u_stress/agent_00/tx_flit_cnt[6]} {u_stress/agent_00/tx_flit_cnt[7]} {u_stress/agent_00/tx_flit_cnt[8]} {u_stress/agent_00/tx_flit_cnt[9]} {u_stress/agent_00/tx_flit_cnt[10]} {u_stress/agent_00/tx_flit_cnt[11]} {u_stress/agent_00/tx_flit_cnt[12]} {u_stress/agent_00/tx_flit_cnt[13]} {u_stress/agent_00/tx_flit_cnt[14]} {u_stress/agent_00/tx_flit_cnt[15]} {u_stress/agent_00/tx_flit_cnt[16]} {u_stress/agent_00/tx_flit_cnt[17]} {u_stress/agent_00/tx_flit_cnt[18]} {u_stress/agent_00/tx_flit_cnt[19]} {u_stress/agent_00/tx_flit_cnt[20]} {u_stress/agent_00/tx_flit_cnt[21]} {u_stress/agent_00/tx_flit_cnt[22]} {u_stress/agent_00/tx_flit_cnt[23]} {u_stress/agent_00/tx_flit_cnt[24]} {u_stress/agent_00/tx_flit_cnt[25]} {u_stress/agent_00/tx_flit_cnt[26]} {u_stress/agent_00/tx_flit_cnt[27]} {u_stress/agent_00/tx_flit_cnt[28]} {u_stress/agent_00/tx_flit_cnt[29]} {u_stress/agent_00/tx_flit_cnt[30]} {u_stress/agent_00/tx_flit_cnt[31]}]]
set_property src_info {type:XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_2 probe
set_property src_info {type:XDC file:1 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe6]
set_property src_info {type:XDC file:1 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_2/probe6]
set_property src_info {type:XDC file:1 line:146 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe6 [get_nets [list {u_stress/agent_00/tx_stall_cnt[0]} {u_stress/agent_00/tx_stall_cnt[1]} {u_stress/agent_00/tx_stall_cnt[2]} {u_stress/agent_00/tx_stall_cnt[3]} {u_stress/agent_00/tx_stall_cnt[4]} {u_stress/agent_00/tx_stall_cnt[5]} {u_stress/agent_00/tx_stall_cnt[6]} {u_stress/agent_00/tx_stall_cnt[7]} {u_stress/agent_00/tx_stall_cnt[8]} {u_stress/agent_00/tx_stall_cnt[9]} {u_stress/agent_00/tx_stall_cnt[10]} {u_stress/agent_00/tx_stall_cnt[11]} {u_stress/agent_00/tx_stall_cnt[12]} {u_stress/agent_00/tx_stall_cnt[13]} {u_stress/agent_00/tx_stall_cnt[14]} {u_stress/agent_00/tx_stall_cnt[15]} {u_stress/agent_00/tx_stall_cnt[16]} {u_stress/agent_00/tx_stall_cnt[17]} {u_stress/agent_00/tx_stall_cnt[18]} {u_stress/agent_00/tx_stall_cnt[19]} {u_stress/agent_00/tx_stall_cnt[20]} {u_stress/agent_00/tx_stall_cnt[21]} {u_stress/agent_00/tx_stall_cnt[22]} {u_stress/agent_00/tx_stall_cnt[23]} {u_stress/agent_00/tx_stall_cnt[24]} {u_stress/agent_00/tx_stall_cnt[25]} {u_stress/agent_00/tx_stall_cnt[26]} {u_stress/agent_00/tx_stall_cnt[27]} {u_stress/agent_00/tx_stall_cnt[28]} {u_stress/agent_00/tx_stall_cnt[29]} {u_stress/agent_00/tx_stall_cnt[30]} {u_stress/agent_00/tx_stall_cnt[31]}]]
set_property src_info {type:XDC file:1 line:147 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_2 probe
set_property src_info {type:XDC file:1 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe7]
set_property src_info {type:XDC file:1 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_2/probe7]
set_property src_info {type:XDC file:1 line:150 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe7 [get_nets [list u_stress/agent_00/test_done]]
set_property src_info {type:XDC file:1 line:151 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_3 ila
set_property src_info {type:XDC file:1 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_3]
set_property src_info {type:XDC file:1 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_3]
set_property src_info {type:XDC file:1 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_3]
set_property src_info {type:XDC file:1 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_3]
set_property src_info {type:XDC file:1 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_3]
set_property src_info {type:XDC file:1 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_3]
set_property src_info {type:XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_3]
set_property src_info {type:XDC file:1 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_3]
set_property src_info {type:XDC file:1 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_3/clk]
set_property src_info {type:XDC file:1 line:161 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_3/clk [get_nets [list clk_gen/inst/clk_out5]]
set_property src_info {type:XDC file:1 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_3/probe0]
set_property src_info {type:XDC file:1 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_3/probe0]
set_property src_info {type:XDC file:1 line:164 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_3/probe0 [get_nets [list {u_stress/agent_11/state_dbg[0]} {u_stress/agent_11/state_dbg[1]}]]
set_property src_info {type:XDC file:1 line:165 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_3 probe
set_property src_info {type:XDC file:1 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_3/probe1]
set_property src_info {type:XDC file:1 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_3/probe1]
set_property src_info {type:XDC file:1 line:168 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_3/probe1 [get_nets [list {u_stress/agent_11/tx_flit_cnt[0]} {u_stress/agent_11/tx_flit_cnt[1]} {u_stress/agent_11/tx_flit_cnt[2]} {u_stress/agent_11/tx_flit_cnt[3]} {u_stress/agent_11/tx_flit_cnt[4]} {u_stress/agent_11/tx_flit_cnt[5]} {u_stress/agent_11/tx_flit_cnt[6]} {u_stress/agent_11/tx_flit_cnt[7]} {u_stress/agent_11/tx_flit_cnt[8]} {u_stress/agent_11/tx_flit_cnt[9]} {u_stress/agent_11/tx_flit_cnt[10]} {u_stress/agent_11/tx_flit_cnt[11]} {u_stress/agent_11/tx_flit_cnt[12]} {u_stress/agent_11/tx_flit_cnt[13]} {u_stress/agent_11/tx_flit_cnt[14]} {u_stress/agent_11/tx_flit_cnt[15]} {u_stress/agent_11/tx_flit_cnt[16]} {u_stress/agent_11/tx_flit_cnt[17]} {u_stress/agent_11/tx_flit_cnt[18]} {u_stress/agent_11/tx_flit_cnt[19]} {u_stress/agent_11/tx_flit_cnt[20]} {u_stress/agent_11/tx_flit_cnt[21]} {u_stress/agent_11/tx_flit_cnt[22]} {u_stress/agent_11/tx_flit_cnt[23]} {u_stress/agent_11/tx_flit_cnt[24]} {u_stress/agent_11/tx_flit_cnt[25]} {u_stress/agent_11/tx_flit_cnt[26]} {u_stress/agent_11/tx_flit_cnt[27]} {u_stress/agent_11/tx_flit_cnt[28]} {u_stress/agent_11/tx_flit_cnt[29]} {u_stress/agent_11/tx_flit_cnt[30]} {u_stress/agent_11/tx_flit_cnt[31]}]]
set_property src_info {type:XDC file:1 line:169 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_3 probe
set_property src_info {type:XDC file:1 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_3/probe2]
set_property src_info {type:XDC file:1 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_3/probe2]
set_property src_info {type:XDC file:1 line:172 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_3/probe2 [get_nets [list {u_stress/agent_11/tx_stall_cnt[0]} {u_stress/agent_11/tx_stall_cnt[1]} {u_stress/agent_11/tx_stall_cnt[2]} {u_stress/agent_11/tx_stall_cnt[3]} {u_stress/agent_11/tx_stall_cnt[4]} {u_stress/agent_11/tx_stall_cnt[5]} {u_stress/agent_11/tx_stall_cnt[6]} {u_stress/agent_11/tx_stall_cnt[7]} {u_stress/agent_11/tx_stall_cnt[8]} {u_stress/agent_11/tx_stall_cnt[9]} {u_stress/agent_11/tx_stall_cnt[10]} {u_stress/agent_11/tx_stall_cnt[11]} {u_stress/agent_11/tx_stall_cnt[12]} {u_stress/agent_11/tx_stall_cnt[13]} {u_stress/agent_11/tx_stall_cnt[14]} {u_stress/agent_11/tx_stall_cnt[15]} {u_stress/agent_11/tx_stall_cnt[16]} {u_stress/agent_11/tx_stall_cnt[17]} {u_stress/agent_11/tx_stall_cnt[18]} {u_stress/agent_11/tx_stall_cnt[19]} {u_stress/agent_11/tx_stall_cnt[20]} {u_stress/agent_11/tx_stall_cnt[21]} {u_stress/agent_11/tx_stall_cnt[22]} {u_stress/agent_11/tx_stall_cnt[23]} {u_stress/agent_11/tx_stall_cnt[24]} {u_stress/agent_11/tx_stall_cnt[25]} {u_stress/agent_11/tx_stall_cnt[26]} {u_stress/agent_11/tx_stall_cnt[27]} {u_stress/agent_11/tx_stall_cnt[28]} {u_stress/agent_11/tx_stall_cnt[29]} {u_stress/agent_11/tx_stall_cnt[30]} {u_stress/agent_11/tx_stall_cnt[31]}]]
set_property src_info {type:XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_3 probe
set_property src_info {type:XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_3/probe3]
set_property src_info {type:XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_3/probe3]
set_property src_info {type:XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_3/probe3 [get_nets [list {u_stress/agent_11/rx_vc1_cnt[0]} {u_stress/agent_11/rx_vc1_cnt[1]} {u_stress/agent_11/rx_vc1_cnt[2]} {u_stress/agent_11/rx_vc1_cnt[3]} {u_stress/agent_11/rx_vc1_cnt[4]} {u_stress/agent_11/rx_vc1_cnt[5]} {u_stress/agent_11/rx_vc1_cnt[6]} {u_stress/agent_11/rx_vc1_cnt[7]} {u_stress/agent_11/rx_vc1_cnt[8]} {u_stress/agent_11/rx_vc1_cnt[9]} {u_stress/agent_11/rx_vc1_cnt[10]} {u_stress/agent_11/rx_vc1_cnt[11]} {u_stress/agent_11/rx_vc1_cnt[12]} {u_stress/agent_11/rx_vc1_cnt[13]} {u_stress/agent_11/rx_vc1_cnt[14]} {u_stress/agent_11/rx_vc1_cnt[15]} {u_stress/agent_11/rx_vc1_cnt[16]} {u_stress/agent_11/rx_vc1_cnt[17]} {u_stress/agent_11/rx_vc1_cnt[18]} {u_stress/agent_11/rx_vc1_cnt[19]} {u_stress/agent_11/rx_vc1_cnt[20]} {u_stress/agent_11/rx_vc1_cnt[21]} {u_stress/agent_11/rx_vc1_cnt[22]} {u_stress/agent_11/rx_vc1_cnt[23]} {u_stress/agent_11/rx_vc1_cnt[24]} {u_stress/agent_11/rx_vc1_cnt[25]} {u_stress/agent_11/rx_vc1_cnt[26]} {u_stress/agent_11/rx_vc1_cnt[27]} {u_stress/agent_11/rx_vc1_cnt[28]} {u_stress/agent_11/rx_vc1_cnt[29]} {u_stress/agent_11/rx_vc1_cnt[30]} {u_stress/agent_11/rx_vc1_cnt[31]}]]
set_property src_info {type:XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_3 probe
set_property src_info {type:XDC file:1 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_3/probe4]
set_property src_info {type:XDC file:1 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_3/probe4]
set_property src_info {type:XDC file:1 line:180 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_3/probe4 [get_nets [list {u_stress/agent_11/rx_err_cnt[0]} {u_stress/agent_11/rx_err_cnt[1]} {u_stress/agent_11/rx_err_cnt[2]} {u_stress/agent_11/rx_err_cnt[3]} {u_stress/agent_11/rx_err_cnt[4]} {u_stress/agent_11/rx_err_cnt[5]} {u_stress/agent_11/rx_err_cnt[6]} {u_stress/agent_11/rx_err_cnt[7]} {u_stress/agent_11/rx_err_cnt[8]} {u_stress/agent_11/rx_err_cnt[9]} {u_stress/agent_11/rx_err_cnt[10]} {u_stress/agent_11/rx_err_cnt[11]} {u_stress/agent_11/rx_err_cnt[12]} {u_stress/agent_11/rx_err_cnt[13]} {u_stress/agent_11/rx_err_cnt[14]} {u_stress/agent_11/rx_err_cnt[15]} {u_stress/agent_11/rx_err_cnt[16]} {u_stress/agent_11/rx_err_cnt[17]} {u_stress/agent_11/rx_err_cnt[18]} {u_stress/agent_11/rx_err_cnt[19]} {u_stress/agent_11/rx_err_cnt[20]} {u_stress/agent_11/rx_err_cnt[21]} {u_stress/agent_11/rx_err_cnt[22]} {u_stress/agent_11/rx_err_cnt[23]} {u_stress/agent_11/rx_err_cnt[24]} {u_stress/agent_11/rx_err_cnt[25]} {u_stress/agent_11/rx_err_cnt[26]} {u_stress/agent_11/rx_err_cnt[27]} {u_stress/agent_11/rx_err_cnt[28]} {u_stress/agent_11/rx_err_cnt[29]} {u_stress/agent_11/rx_err_cnt[30]} {u_stress/agent_11/rx_err_cnt[31]}]]
set_property src_info {type:XDC file:1 line:181 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_3 probe
set_property src_info {type:XDC file:1 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_3/probe5]
set_property src_info {type:XDC file:1 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_3/probe5]
set_property src_info {type:XDC file:1 line:184 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_3/probe5 [get_nets [list {u_stress/agent_11/rx_tdest_dbg[0]} {u_stress/agent_11/rx_tdest_dbg[1]} {u_stress/agent_11/rx_tdest_dbg[2]} {u_stress/agent_11/rx_tdest_dbg[3]}]]
set_property src_info {type:XDC file:1 line:185 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_3 probe
set_property src_info {type:XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_3/probe6]
set_property src_info {type:XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_3/probe6]
set_property src_info {type:XDC file:1 line:188 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_3/probe6 [get_nets [list {u_stress/agent_11/rx_vc0_cnt[0]} {u_stress/agent_11/rx_vc0_cnt[1]} {u_stress/agent_11/rx_vc0_cnt[2]} {u_stress/agent_11/rx_vc0_cnt[3]} {u_stress/agent_11/rx_vc0_cnt[4]} {u_stress/agent_11/rx_vc0_cnt[5]} {u_stress/agent_11/rx_vc0_cnt[6]} {u_stress/agent_11/rx_vc0_cnt[7]} {u_stress/agent_11/rx_vc0_cnt[8]} {u_stress/agent_11/rx_vc0_cnt[9]} {u_stress/agent_11/rx_vc0_cnt[10]} {u_stress/agent_11/rx_vc0_cnt[11]} {u_stress/agent_11/rx_vc0_cnt[12]} {u_stress/agent_11/rx_vc0_cnt[13]} {u_stress/agent_11/rx_vc0_cnt[14]} {u_stress/agent_11/rx_vc0_cnt[15]} {u_stress/agent_11/rx_vc0_cnt[16]} {u_stress/agent_11/rx_vc0_cnt[17]} {u_stress/agent_11/rx_vc0_cnt[18]} {u_stress/agent_11/rx_vc0_cnt[19]} {u_stress/agent_11/rx_vc0_cnt[20]} {u_stress/agent_11/rx_vc0_cnt[21]} {u_stress/agent_11/rx_vc0_cnt[22]} {u_stress/agent_11/rx_vc0_cnt[23]} {u_stress/agent_11/rx_vc0_cnt[24]} {u_stress/agent_11/rx_vc0_cnt[25]} {u_stress/agent_11/rx_vc0_cnt[26]} {u_stress/agent_11/rx_vc0_cnt[27]} {u_stress/agent_11/rx_vc0_cnt[28]} {u_stress/agent_11/rx_vc0_cnt[29]} {u_stress/agent_11/rx_vc0_cnt[30]} {u_stress/agent_11/rx_vc0_cnt[31]}]]
set_property src_info {type:XDC file:1 line:189 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_3 probe
set_property src_info {type:XDC file:1 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_3/probe7]
set_property src_info {type:XDC file:1 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_3/probe7]
set_property src_info {type:XDC file:1 line:192 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_3/probe7 [get_nets [list u_stress/agent_11/test_done]]
set_property src_info {type:XDC file:1 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:196 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets clk_h10]
