# connect_debug_port u_ila_0/probe0 [get_nets [list {echo_11/count_dbg[0]} {echo_11/count_dbg[1]} {echo_11/count_dbg[2]} {echo_11/count_dbg[3]}]]
# connect_debug_port u_ila_0/probe3 [get_nets [list echo_11/tx_tready_dbg]]
# connect_debug_port u_ila_1/probe0 [get_nets [list {echo_10/count_dbg[0]} {echo_10/count_dbg[1]} {echo_10/count_dbg[2]} {echo_10/count_dbg[3]}]]
# connect_debug_port u_ila_1/probe3 [get_nets [list echo_10/tx_tready_dbg]]
# connect_debug_port u_ila_2/probe0 [get_nets [list {echo_01/count_dbg[0]} {echo_01/count_dbg[1]} {echo_01/count_dbg[2]} {echo_01/count_dbg[3]}]]
# connect_debug_port u_ila_2/probe3 [get_nets [list echo_01/tx_tready_dbg]]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_gen/inst/clk_out5]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {echo_11/cnt0_dbg[0]} {echo_11/cnt0_dbg[1]} {echo_11/cnt0_dbg[2]} {echo_11/cnt0_dbg[3]} {echo_11/cnt0_dbg[4]} {echo_11/cnt0_dbg[5]} {echo_11/cnt0_dbg[6]} {echo_11/cnt0_dbg[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 8 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {echo_11/cnt1_dbg[0]} {echo_11/cnt1_dbg[1]} {echo_11/cnt1_dbg[2]} {echo_11/cnt1_dbg[3]} {echo_11/cnt1_dbg[4]} {echo_11/cnt1_dbg[5]} {echo_11/cnt1_dbg[6]} {echo_11/cnt1_dbg[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 2 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {echo_11/tx_tid_dbg[0]} {echo_11/tx_tid_dbg[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 2 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {echo_11/rx_tid_dbg[0]} {echo_11/rx_tid_dbg[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 8 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {echo_11/tx_tdata_dbg[0]} {echo_11/tx_tdata_dbg[1]} {echo_11/tx_tdata_dbg[2]} {echo_11/tx_tdata_dbg[3]} {echo_11/tx_tdata_dbg[4]} {echo_11/tx_tdata_dbg[5]} {echo_11/tx_tdata_dbg[6]} {echo_11/tx_tdata_dbg[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 4 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {echo_11/rx_tdest_dbg[0]} {echo_11/rx_tdest_dbg[1]} {echo_11/rx_tdest_dbg[2]} {echo_11/rx_tdest_dbg[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 2 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {echo_11/tx_tready_dbg[0]} {echo_11/tx_tready_dbg[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list echo_11/rx_tvalid_dbg]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list echo_11/tx_tlast_dbg]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list echo_11/tx_tvalid_dbg]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list clk_gen/inst/clk_out3]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 4 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {echo_01/rx_tdest_dbg[0]} {echo_01/rx_tdest_dbg[1]} {echo_01/rx_tdest_dbg[2]} {echo_01/rx_tdest_dbg[3]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 2 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list {echo_01/rx_tid_dbg[0]} {echo_01/rx_tid_dbg[1]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe2]
set_property port_width 8 [get_debug_ports u_ila_1/probe2]
connect_debug_port u_ila_1/probe2 [get_nets [list {echo_01/tx_tdata_dbg[0]} {echo_01/tx_tdata_dbg[1]} {echo_01/tx_tdata_dbg[2]} {echo_01/tx_tdata_dbg[3]} {echo_01/tx_tdata_dbg[4]} {echo_01/tx_tdata_dbg[5]} {echo_01/tx_tdata_dbg[6]} {echo_01/tx_tdata_dbg[7]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe3]
set_property port_width 2 [get_debug_ports u_ila_1/probe3]
connect_debug_port u_ila_1/probe3 [get_nets [list {echo_01/tx_tid_dbg[0]} {echo_01/tx_tid_dbg[1]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe4]
set_property port_width 8 [get_debug_ports u_ila_1/probe4]
connect_debug_port u_ila_1/probe4 [get_nets [list {echo_01/cnt1_dbg[0]} {echo_01/cnt1_dbg[1]} {echo_01/cnt1_dbg[2]} {echo_01/cnt1_dbg[3]} {echo_01/cnt1_dbg[4]} {echo_01/cnt1_dbg[5]} {echo_01/cnt1_dbg[6]} {echo_01/cnt1_dbg[7]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe5]
set_property port_width 8 [get_debug_ports u_ila_1/probe5]
connect_debug_port u_ila_1/probe5 [get_nets [list {echo_01/cnt0_dbg[0]} {echo_01/cnt0_dbg[1]} {echo_01/cnt0_dbg[2]} {echo_01/cnt0_dbg[3]} {echo_01/cnt0_dbg[4]} {echo_01/cnt0_dbg[5]} {echo_01/cnt0_dbg[6]} {echo_01/cnt0_dbg[7]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe6]
set_property port_width 2 [get_debug_ports u_ila_1/probe6]
connect_debug_port u_ila_1/probe6 [get_nets [list {echo_01/tx_tready_dbg[0]} {echo_01/tx_tready_dbg[1]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe7]
set_property port_width 1 [get_debug_ports u_ila_1/probe7]
connect_debug_port u_ila_1/probe7 [get_nets [list echo_01/rx_tvalid_dbg]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe8]
set_property port_width 1 [get_debug_ports u_ila_1/probe8]
connect_debug_port u_ila_1/probe8 [get_nets [list echo_01/tx_tlast_dbg]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe9]
set_property port_width 1 [get_debug_ports u_ila_1/probe9]
connect_debug_port u_ila_1/probe9 [get_nets [list echo_01/tx_tvalid_dbg]]
create_debug_core u_ila_2 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_2]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_2]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_2]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_2]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_2]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_2]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_2]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_2]
set_property port_width 1 [get_debug_ports u_ila_2/clk]
connect_debug_port u_ila_2/clk [get_nets [list clk_gen/inst/clk_out4]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe0]
set_property port_width 4 [get_debug_ports u_ila_2/probe0]
connect_debug_port u_ila_2/probe0 [get_nets [list {echo_10/rx_tdest_dbg[0]} {echo_10/rx_tdest_dbg[1]} {echo_10/rx_tdest_dbg[2]} {echo_10/rx_tdest_dbg[3]}]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe1]
set_property port_width 2 [get_debug_ports u_ila_2/probe1]
connect_debug_port u_ila_2/probe1 [get_nets [list {echo_10/tx_tready_dbg[0]} {echo_10/tx_tready_dbg[1]}]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe2]
set_property port_width 2 [get_debug_ports u_ila_2/probe2]
connect_debug_port u_ila_2/probe2 [get_nets [list {echo_10/tx_tid_dbg[0]} {echo_10/tx_tid_dbg[1]}]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe3]
set_property port_width 8 [get_debug_ports u_ila_2/probe3]
connect_debug_port u_ila_2/probe3 [get_nets [list {echo_10/cnt1_dbg[0]} {echo_10/cnt1_dbg[1]} {echo_10/cnt1_dbg[2]} {echo_10/cnt1_dbg[3]} {echo_10/cnt1_dbg[4]} {echo_10/cnt1_dbg[5]} {echo_10/cnt1_dbg[6]} {echo_10/cnt1_dbg[7]}]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe4]
set_property port_width 8 [get_debug_ports u_ila_2/probe4]
connect_debug_port u_ila_2/probe4 [get_nets [list {echo_10/cnt0_dbg[0]} {echo_10/cnt0_dbg[1]} {echo_10/cnt0_dbg[2]} {echo_10/cnt0_dbg[3]} {echo_10/cnt0_dbg[4]} {echo_10/cnt0_dbg[5]} {echo_10/cnt0_dbg[6]} {echo_10/cnt0_dbg[7]}]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe5]
set_property port_width 2 [get_debug_ports u_ila_2/probe5]
connect_debug_port u_ila_2/probe5 [get_nets [list {echo_10/rx_tid_dbg[0]} {echo_10/rx_tid_dbg[1]}]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe6]
set_property port_width 8 [get_debug_ports u_ila_2/probe6]
connect_debug_port u_ila_2/probe6 [get_nets [list {echo_10/tx_tdata_dbg[0]} {echo_10/tx_tdata_dbg[1]} {echo_10/tx_tdata_dbg[2]} {echo_10/tx_tdata_dbg[3]} {echo_10/tx_tdata_dbg[4]} {echo_10/tx_tdata_dbg[5]} {echo_10/tx_tdata_dbg[6]} {echo_10/tx_tdata_dbg[7]}]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe7]
set_property port_width 1 [get_debug_ports u_ila_2/probe7]
connect_debug_port u_ila_2/probe7 [get_nets [list echo_10/rx_tvalid_dbg]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe8]
set_property port_width 1 [get_debug_ports u_ila_2/probe8]
connect_debug_port u_ila_2/probe8 [get_nets [list echo_10/tx_tlast_dbg]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe9]
set_property port_width 1 [get_debug_ports u_ila_2/probe9]
connect_debug_port u_ila_2/probe9 [get_nets [list echo_10/tx_tvalid_dbg]]
create_debug_core u_ila_3 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_3]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_3]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_3]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_3]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_3]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_3]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_3]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_3]
set_property port_width 1 [get_debug_ports u_ila_3/clk]
connect_debug_port u_ila_3/clk [get_nets [list clk_gen/inst/clk_out2]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_3/probe0]
set_property port_width 2 [get_debug_ports u_ila_3/probe0]
connect_debug_port u_ila_3/probe0 [get_nets [list {host_00/d_state_dbg[0]} {host_00/d_state_dbg[1]}]]
create_debug_port u_ila_3 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_3/probe1]
set_property port_width 2 [get_debug_ports u_ila_3/probe1]
connect_debug_port u_ila_3/probe1 [get_nets [list {host_00/p_state_dbg[0]} {host_00/p_state_dbg[1]}]]
create_debug_port u_ila_3 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_3/probe2]
set_property port_width 8 [get_debug_ports u_ila_3/probe2]
connect_debug_port u_ila_3/probe2 [get_nets [list {host_00/noc_data_reg_dbg[0]} {host_00/noc_data_reg_dbg[1]} {host_00/noc_data_reg_dbg[2]} {host_00/noc_data_reg_dbg[3]} {host_00/noc_data_reg_dbg[4]} {host_00/noc_data_reg_dbg[5]} {host_00/noc_data_reg_dbg[6]} {host_00/noc_data_reg_dbg[7]}]]
create_debug_port u_ila_3 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_3/probe3]
set_property port_width 2 [get_debug_ports u_ila_3/probe3]
connect_debug_port u_ila_3/probe3 [get_nets [list {host_00/rx_tid_dbg[0]} {host_00/rx_tid_dbg[1]}]]
create_debug_port u_ila_3 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_3/probe4]
set_property port_width 8 [get_debug_ports u_ila_3/probe4]
connect_debug_port u_ila_3/probe4 [get_nets [list {host_00/tx_tdata_dbg[0]} {host_00/tx_tdata_dbg[1]} {host_00/tx_tdata_dbg[2]} {host_00/tx_tdata_dbg[3]} {host_00/tx_tdata_dbg[4]} {host_00/tx_tdata_dbg[5]} {host_00/tx_tdata_dbg[6]} {host_00/tx_tdata_dbg[7]}]]
create_debug_port u_ila_3 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_3/probe5]
set_property port_width 8 [get_debug_ports u_ila_3/probe5]
connect_debug_port u_ila_3/probe5 [get_nets [list {host_00/rx_tdata_dbg[0]} {host_00/rx_tdata_dbg[1]} {host_00/rx_tdata_dbg[2]} {host_00/rx_tdata_dbg[3]} {host_00/rx_tdata_dbg[4]} {host_00/rx_tdata_dbg[5]} {host_00/rx_tdata_dbg[6]} {host_00/rx_tdata_dbg[7]}]]
create_debug_port u_ila_3 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_3/probe6]
set_property port_width 1 [get_debug_ports u_ila_3/probe6]
connect_debug_port u_ila_3/probe6 [get_nets [list host_00/rx_tvalid_dbg]]
create_debug_port u_ila_3 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_3/probe7]
set_property port_width 1 [get_debug_ports u_ila_3/probe7]
connect_debug_port u_ila_3/probe7 [get_nets [list host_00/uart_tx_ready_dbg]]
create_debug_port u_ila_3 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_3/probe8]
set_property port_width 1 [get_debug_ports u_ila_3/probe8]
connect_debug_port u_ila_3/probe8 [get_nets [list host_00/uart_tx_valid_dbg]]
create_debug_core u_ila_4 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_4]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_4]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_4]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_4]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_4]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_4]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_4]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_4]
set_property port_width 1 [get_debug_ports u_ila_4/clk]
# connect_debug_port u_ila_4/clk [get_nets [list clk_gen/inst/clkfbout_buf_clk_wiz_0]]
connect_debug_port u_ila_4/clk [get_nets [list clk_gen/inst/clk_out2]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_4/probe0]
set_property port_width 32 [get_debug_ports u_ila_4/probe0]
connect_debug_port u_ila_4/probe0 [get_nets [list {uut_noc_top/mon_flit_cnt[0]} {uut_noc_top/mon_flit_cnt[1]} {uut_noc_top/mon_flit_cnt[2]} {uut_noc_top/mon_flit_cnt[3]} {uut_noc_top/mon_flit_cnt[4]} {uut_noc_top/mon_flit_cnt[5]} {uut_noc_top/mon_flit_cnt[6]} {uut_noc_top/mon_flit_cnt[7]} {uut_noc_top/mon_flit_cnt[8]} {uut_noc_top/mon_flit_cnt[9]} {uut_noc_top/mon_flit_cnt[10]} {uut_noc_top/mon_flit_cnt[11]} {uut_noc_top/mon_flit_cnt[12]} {uut_noc_top/mon_flit_cnt[13]} {uut_noc_top/mon_flit_cnt[14]} {uut_noc_top/mon_flit_cnt[15]} {uut_noc_top/mon_flit_cnt[16]} {uut_noc_top/mon_flit_cnt[17]} {uut_noc_top/mon_flit_cnt[18]} {uut_noc_top/mon_flit_cnt[19]} {uut_noc_top/mon_flit_cnt[20]} {uut_noc_top/mon_flit_cnt[21]} {uut_noc_top/mon_flit_cnt[22]} {uut_noc_top/mon_flit_cnt[23]} {uut_noc_top/mon_flit_cnt[24]} {uut_noc_top/mon_flit_cnt[25]} {uut_noc_top/mon_flit_cnt[26]} {uut_noc_top/mon_flit_cnt[27]} {uut_noc_top/mon_flit_cnt[28]} {uut_noc_top/mon_flit_cnt[29]} {uut_noc_top/mon_flit_cnt[30]} {uut_noc_top/mon_flit_cnt[31]}]]
create_debug_port u_ila_4 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_4/probe1]
set_property port_width 32 [get_debug_ports u_ila_4/probe1]
connect_debug_port u_ila_4/probe1 [get_nets [list {uut_noc_top/mon_pkt_cnt[0]} {uut_noc_top/mon_pkt_cnt[1]} {uut_noc_top/mon_pkt_cnt[2]} {uut_noc_top/mon_pkt_cnt[3]} {uut_noc_top/mon_pkt_cnt[4]} {uut_noc_top/mon_pkt_cnt[5]} {uut_noc_top/mon_pkt_cnt[6]} {uut_noc_top/mon_pkt_cnt[7]} {uut_noc_top/mon_pkt_cnt[8]} {uut_noc_top/mon_pkt_cnt[9]} {uut_noc_top/mon_pkt_cnt[10]} {uut_noc_top/mon_pkt_cnt[11]} {uut_noc_top/mon_pkt_cnt[12]} {uut_noc_top/mon_pkt_cnt[13]} {uut_noc_top/mon_pkt_cnt[14]} {uut_noc_top/mon_pkt_cnt[15]} {uut_noc_top/mon_pkt_cnt[16]} {uut_noc_top/mon_pkt_cnt[17]} {uut_noc_top/mon_pkt_cnt[18]} {uut_noc_top/mon_pkt_cnt[19]} {uut_noc_top/mon_pkt_cnt[20]} {uut_noc_top/mon_pkt_cnt[21]} {uut_noc_top/mon_pkt_cnt[22]} {uut_noc_top/mon_pkt_cnt[23]} {uut_noc_top/mon_pkt_cnt[24]} {uut_noc_top/mon_pkt_cnt[25]} {uut_noc_top/mon_pkt_cnt[26]} {uut_noc_top/mon_pkt_cnt[27]} {uut_noc_top/mon_pkt_cnt[28]} {uut_noc_top/mon_pkt_cnt[29]} {uut_noc_top/mon_pkt_cnt[30]} {uut_noc_top/mon_pkt_cnt[31]}]]
create_debug_port u_ila_4 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_4/probe2]
set_property port_width 32 [get_debug_ports u_ila_4/probe2]
connect_debug_port u_ila_4/probe2 [get_nets [list {uut_noc_top/mon_stall_cnt[0]} {uut_noc_top/mon_stall_cnt[1]} {uut_noc_top/mon_stall_cnt[2]} {uut_noc_top/mon_stall_cnt[3]} {uut_noc_top/mon_stall_cnt[4]} {uut_noc_top/mon_stall_cnt[5]} {uut_noc_top/mon_stall_cnt[6]} {uut_noc_top/mon_stall_cnt[7]} {uut_noc_top/mon_stall_cnt[8]} {uut_noc_top/mon_stall_cnt[9]} {uut_noc_top/mon_stall_cnt[10]} {uut_noc_top/mon_stall_cnt[11]} {uut_noc_top/mon_stall_cnt[12]} {uut_noc_top/mon_stall_cnt[13]} {uut_noc_top/mon_stall_cnt[14]} {uut_noc_top/mon_stall_cnt[15]} {uut_noc_top/mon_stall_cnt[16]} {uut_noc_top/mon_stall_cnt[17]} {uut_noc_top/mon_stall_cnt[18]} {uut_noc_top/mon_stall_cnt[19]} {uut_noc_top/mon_stall_cnt[20]} {uut_noc_top/mon_stall_cnt[21]} {uut_noc_top/mon_stall_cnt[22]} {uut_noc_top/mon_stall_cnt[23]} {uut_noc_top/mon_stall_cnt[24]} {uut_noc_top/mon_stall_cnt[25]} {uut_noc_top/mon_stall_cnt[26]} {uut_noc_top/mon_stall_cnt[27]} {uut_noc_top/mon_stall_cnt[28]} {uut_noc_top/mon_stall_cnt[29]} {uut_noc_top/mon_stall_cnt[30]} {uut_noc_top/mon_stall_cnt[31]}]]
create_debug_port u_ila_4 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_4/probe3]
set_property port_width 32 [get_debug_ports u_ila_4/probe3]
connect_debug_port u_ila_4/probe3 [get_nets [list {uut_noc_top/mon_active_cnt[0]} {uut_noc_top/mon_active_cnt[1]} {uut_noc_top/mon_active_cnt[2]} {uut_noc_top/mon_active_cnt[3]} {uut_noc_top/mon_active_cnt[4]} {uut_noc_top/mon_active_cnt[5]} {uut_noc_top/mon_active_cnt[6]} {uut_noc_top/mon_active_cnt[7]} {uut_noc_top/mon_active_cnt[8]} {uut_noc_top/mon_active_cnt[9]} {uut_noc_top/mon_active_cnt[10]} {uut_noc_top/mon_active_cnt[11]} {uut_noc_top/mon_active_cnt[12]} {uut_noc_top/mon_active_cnt[13]} {uut_noc_top/mon_active_cnt[14]} {uut_noc_top/mon_active_cnt[15]} {uut_noc_top/mon_active_cnt[16]} {uut_noc_top/mon_active_cnt[17]} {uut_noc_top/mon_active_cnt[18]} {uut_noc_top/mon_active_cnt[19]} {uut_noc_top/mon_active_cnt[20]} {uut_noc_top/mon_active_cnt[21]} {uut_noc_top/mon_active_cnt[22]} {uut_noc_top/mon_active_cnt[23]} {uut_noc_top/mon_active_cnt[24]} {uut_noc_top/mon_active_cnt[25]} {uut_noc_top/mon_active_cnt[26]} {uut_noc_top/mon_active_cnt[27]} {uut_noc_top/mon_active_cnt[28]} {uut_noc_top/mon_active_cnt[29]} {uut_noc_top/mon_active_cnt[30]} {uut_noc_top/mon_active_cnt[31]}]]
# set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_CLK_INPUT_FREQ_HZ 71428571 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_h11]
